//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace direcciones.direccion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="direccion.direccionIPSoap")]
    public interface direccionIPSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento direccionResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/direccion", ReplyAction="*")]
        direcciones.direccion.direccionResponse direccion(direcciones.direccion.direccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/direccion", ReplyAction="*")]
        System.Threading.Tasks.Task<direcciones.direccion.direccionResponse> direccionAsync(direcciones.direccion.direccionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class direccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="direccion", Namespace="http://tempuri.org/", Order=0)]
        public direcciones.direccion.direccionRequestBody Body;
        
        public direccionRequest() {
        }
        
        public direccionRequest(direcciones.direccion.direccionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class direccionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ip;
        
        public direccionRequestBody() {
        }
        
        public direccionRequestBody(int ip) {
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class direccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="direccionResponse", Namespace="http://tempuri.org/", Order=0)]
        public direcciones.direccion.direccionResponseBody Body;
        
        public direccionResponse() {
        }
        
        public direccionResponse(direcciones.direccion.direccionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class direccionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string direccionResult;
        
        public direccionResponseBody() {
        }
        
        public direccionResponseBody(string direccionResult) {
            this.direccionResult = direccionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface direccionIPSoapChannel : direcciones.direccion.direccionIPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class direccionIPSoapClient : System.ServiceModel.ClientBase<direcciones.direccion.direccionIPSoap>, direcciones.direccion.direccionIPSoap {
        
        public direccionIPSoapClient() {
        }
        
        public direccionIPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public direccionIPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public direccionIPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public direccionIPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        direcciones.direccion.direccionResponse direcciones.direccion.direccionIPSoap.direccion(direcciones.direccion.direccionRequest request) {
            return base.Channel.direccion(request);
        }
        
        public string direccion(int ip) {
            direcciones.direccion.direccionRequest inValue = new direcciones.direccion.direccionRequest();
            inValue.Body = new direcciones.direccion.direccionRequestBody();
            inValue.Body.ip = ip;
            direcciones.direccion.direccionResponse retVal = ((direcciones.direccion.direccionIPSoap)(this)).direccion(inValue);
            return retVal.Body.direccionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<direcciones.direccion.direccionResponse> direcciones.direccion.direccionIPSoap.direccionAsync(direcciones.direccion.direccionRequest request) {
            return base.Channel.direccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<direcciones.direccion.direccionResponse> direccionAsync(int ip) {
            direcciones.direccion.direccionRequest inValue = new direcciones.direccion.direccionRequest();
            inValue.Body = new direcciones.direccion.direccionRequestBody();
            inValue.Body.ip = ip;
            return ((direcciones.direccion.direccionIPSoap)(this)).direccionAsync(inValue);
        }
    }
}
